env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent: # indentation is 2 spaces
    - error
    - 2
  linebreak-style: # use unix linebreak (\n)
    - error
    - unix
  quotes: # single quotes (or backticks if there is a substitution)
    - error
    - single
  semi: # semicolons are required
    - error
    - always
  no-console: # console.log(...) is allowed
    - off
