version: '2'
services:
  linkurious:
    build:
      context: .
      args:
        ci_directory: ${CI_DIRECTORY}
    depends_on:
     - dse
     - elasticsearch
  dse:
    build:
      context: ./dse
    environment:
     - LISTEN_ADDRESS=dse
  elasticsearch:
    image: elasticsearch:1.7
