version: '2'
services:
  linkurious:
    build:
      context: .
      args:
        ci_directory: ${CI_DIRECTORY}
    depends_on:
     - neo4j
     - elasticsearch
  neo4j:
    image: neo4j:3.0
    environment:
     - NEO4J_AUTH=none
  elasticsearch:
    image: elasticsearch:2.4
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=linkurious
      - MYSQL_USER=linkurious
      - MYSQL_PASSWORD=pass
